### ISSUE TITLE
Uncaught Timeout Error exception 

### ISSUE THREAD

**Issue by schmupu** [mcollina/node-coap#208]
I am using the lib and I got once the while following error:

```
2019-07-17 00:07:04.975 - error:  { Error: No reply in 247s
2019-07-17 00:07:04.976 - error:  at Timeout._onTimeout (/opt/iobroker/node_modules/coap/lib/retry_send.js:74:16)
2019-07-17 00:07:04.976 - error:  at ontimeout (timers.js:498:11)
2019-07-17 00:07:04.976 - error:  at tryOnTimeout (timers.js:323:5)
2019-07-17 00:07:04.976 - error:  at Timer.listOnTimeout (timers.js:290:5) retransmitTimeout: 247 }
```

Do you have an idea how I can prevent this error?

**Comment by HGlab01** [comment]
@mcollina  Would be really cool to get this solved! Thanx in advance!

**Comment by Apollon77** [comment]
Can be closed, we fixed it by using lib correctly :-)
