### ISSUE TITLE
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds/

### ISSUE THREAD

**Issue by Apollon77** [mcollina/node-coap#216]
Exception:

```
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
at boundsError (internal/buffer.js:47:11)
at Buffer.readUInt32BE (internal/buffer.js:192:5)
at Agent.abort (/opt/iobroker/node_modules/coap/lib/agent.js:404:42)
at RetrySend. (/opt/iobroker/node_modules/coap/lib/agent.js:365:10)
at RetrySend.emit (events.js:198:13)
at Timeout. (/opt/iobroker/node_modules/coap/lib/retry_send.js:78:10)
at ontimeout (timers.js:436:11)
at tryOnTimeout (timers.js:300:5)
at listOnTimeout (timers.js:263:5)
at Timer.processTimers (timers.js:223:10)
```

The reason seems to be that in line https://github.com/mcollina/node-coap/blob/master/lib/agent.js#L407 it is assumed that req._packet.token is a valid buffer from valid length ... but this is not checked here ... and so it seems that in timeout cases or such this exception occurs.

I saw several other places in the code where the same pattern is used (reading that token without checking) ... in many other places it is checked that token exists, in other cases also that length is ===4 ... a bit inconsistent ;-)

If interested I could provide a PR, but I can not really test this case because I do not use such devices :-(

**Comment by maxpd1** [comment]
How can we push this issue as Shelly isn't usable anymore with iobroker as the adapter is every 5 minutes red for 1 minute. Means 25% of the time its offline.

**Comment by muerzi** [comment]
Any News here?
