### ISSUE TITLE
case-insensitive option matching

### ISSUE THREAD

**Issue by boneskull** [mcollina/node-coap#71]
I have something that's trying to send option `content-type`.  This results in:

```
    Error: Unknown string to Buffer converter for option: content-type
    at module.exports.toBinary (/Volumes/alien/projects/digs/tmp/node_modules/coap/lib/option_converter.js:18:11)
    at OutMessage.setOption (/Volumes/alien/projects/digs/tmp/node_modules/coap/lib/helpers.js:46:16)

```

@mcollina Would you accept a PR to just run `.toLowercase()` across the option names?

**Comment by boneskull** [comment]
the fix would be in the helper with the content-format alias, etc

**Comment by mcollina** [comment]
I'm ok for a PR that address both this and #73.
