### ISSUE TITLE
ReferenceError: err is not defined

### ISSUE THREAD

**Issue by neophob** [mcollina/node-coap#87]
I just saw this error in a log file:

```
/usr/lib/node_modules/coap-cli/node_modules/coap/lib/agent.js:180
      return req.emit('error', err)
                              ^

ReferenceError: err is not defined
    at Agent.handle [as _handle] (/usr/lib/node_modules/coap-cli/node_modules/coap/lib/agent.js:180:32)
    at Socket.<anonymous> (/usr/lib/node_modules/coap-cli/node_modules/coap/lib/agent.js:66:10)
    at emitTwo (events.js:87:13)
    at Socket.emit (events.js:172:7)
    at UDP.onMessage (dgram.js:481
```

Currently I cannot reproduce it as I don't know how it happend.

**Comment by mcollina** [comment]
The problem here is that it could not parse block2 https://github.com/mcollina/node-coap/blob/master/lib/agent.js#L180. Would you mind sending a PR to fix the 'err is not defined' thing?

Thanks!

**Comment by neophob** [comment]
Hmm according to the error message and glancing at the code this looks like err is undefined. So replace err with a string (maybe 'failed to parse block2')?
